apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pmfyy7qsl-java-springboot
  janus-idp.io/tekton: pmfyy7qsl-java-springboot
  backstage.io/kubernetes-id: pmfyy7qsl-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pmfyy7qsl-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
